apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: elasticsearch
    spec:
      type: NodePort
      ports:
        - name: client
          port: 9200
          targetPort: 9200
          nodePort: 30920
        - name: transport
          port: 9300
          targetPort: 9300 
      selector:
        app: elasticsearch
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: elasticsearch
    spec:
      serviceName: elasticsearch
      replicas: 1
      selector:
        matchLabels:
          app: elasticsearch
      template:
        metadata:
          labels:
            app: elasticsearch
        spec:
          containers:
            - name: elasticsearch
              image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
              imagePullPolicy: Always
              env:
                - name: discovery.type
                  value: single-node
              ports:
                - containerPort: 9200
                  name: client
                - containerPort: 9300
                  name: transport
              volumeMounts:
              - name: data
                mountPath: /usr/share/elasticsearch/data
          restartPolicy: Always
          volumes:
          - name: data
            emptyDir:
kind: List
metadata: {}