version: '3'
services:
  obp:
    image: "obp-contracts:latest"
    build:
      context: .
    command: "npm run deploy"
    volumes:
      - ./contracts:/app/contracts
      - ./migrations:/app/migrations
      - ./build:/app/build
      - ./truffle-config.js:/app/truffle-config.js
      - ./package.json:/app/package.json
  ganache:
    image: "ganache:latest"
    expose:
      - '7545'
    ports:
      - 7545:7545
    build:
      context: .
    command: "npm run ganache"
    volumes:
      - ./contracts:/app/contracts
      - ./migrations:/app/migrations
      - ./build:/app/build
      - ./truffle-config.js:/app/truffle-config.js
      - ./package.json:/app/package.json

