# Useful References:
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume
# https://kubernetes.io/docs/concepts/storage/storage-classes/#local
# https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocksdb3-pv
  labels:
    app: rocksdb3-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: "/mnt/vmware-blockchain-concord3"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocksdb3-pv-claim
spec:
  storageClassName: standard
  selector:
    matchLabels:
      app: rocksdb3-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi