apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privacy-wallet-app-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
